
image: Visual Studio 2015
platform: x64
version: 1.0.{build}

build_script:
  - git submodule update --init --recursive
  - cd build
  - mkdir win32 win64
  - cd win64
  - cmake -DUSE_LLVM_CONFIG=off -C ../backends/most.cmake -C ../targets/all.cmake .. -G "Visual Studio 14 2015 Win64"
  - cmake --build . --config Release

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
      - orlarey@grame.fr
    subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
